apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - port: 30001
      protocol: TCP
      name: jconsole-port
      nodePort: 30001
    - port: 8088
      protocol: TCP
      name: app
      targetPort: 8088